<?php

use Drupal\Core\Form\FormStateInterface;
use Drupal\webform_sanitize_submissions\Plugin\WebformHandler\SanitizeSubmissionWebformHandler;
use Drupal\webform_ui\Form\WebformUiElementFormInterface;

/**
 * Implements hook_webform_element_default_properties_alter().
 */
function webform_sanitize_submissions_webform_element_default_properties_alter(array &$properties, array &$definition): void {
  $properties['sanitize'] = false;
}

/**
 * Implements hook_webform_element_configuration_form_alter().
 */
function webform_sanitize_submissions_webform_element_configuration_form_alter(array &$form, FormStateInterface $form_state): void {
  $form['sanitation'] = [
    '#type' => 'details',
    '#title' => t('Sanitation'),
    '#open' => TRUE,
    '#group' => 'tab_advanced',
  ];

  $form['sanitation']['sanitize'] = [
    '#type' => 'checkbox',
    '#title' => t('Sanitize element value'),
    '#description' => t("If checked, the element value will be deleted from the database after submission. You can still use the value in webform handlers before the 'Sanitize submission' handler."),
    '#default_value' => $form_state->get('element_settings')['sanitize'] ?? FALSE,
  ];

  // Add a message if the webform handler isn't added yet.
  $formObject = $form_state->getFormObject();
  assert($formObject instanceof WebformUiElementFormInterface);
  $webform = $formObject->getWebform();

  $handlers = array_filter(
    iterator_to_array($webform->getHandlers()),
    fn ($handler) => $handler instanceof SanitizeSubmissionWebformHandler,
  );

  if (count($handlers) === 0) {
    $form['sanitation']['handler_warning'] = [
      '#theme' => 'status_messages',
      '#message_list' => [
        'warning' => [
          t("No 'Sanitize submission' handler has been added to this webform yet, which means that submissions aren't being sanitized automatically. <a href=\"@handlersUrl\">Add one now.</a>", [
            '@handlersUrl' => $webform->toUrl('handlers')->toString(),
          ])
        ],
      ],
      '#status_headings' => ['warning' => t('Warning message')],
      '#access' => TRUE,
    ];
  }
}
